services:  
  zookeeper:  #Zookeeper, a distributed coordination service used by Kafka.
    image: wurstmeister/zookeeper  # updated 5 years ago, but video said is stable version (consider bitnami)
    container_name: zookeeper  # Sets a custom name for the Zookeeper container, making it easier to reference.
    ports:
      - "2181:2181"  # Exposes port 2181 on both the host and the container. Port 2181 is used by Zookeeper to handle client connections.

  kafka: 
    image: wurstmeister/kafka
    container_name: kafka  
    ports:
      - "9092:9092"     # External port for communication with clients
      - "29092:29092"   # Internal port for Kafka brokers
    environment:  # Defines environment variables that will be set inside the Kafka container.
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # Specifies the address (host:port) of the Zookeeper service that Kafka will connect to. (it connects to the 'zookeeper' service running on port 2181 within the Docker Compose network)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092, EXTERNAL://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092, EXTERNAL://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
  
  mongo:
    image: mongo:6.0.5
    container_name: mongo
    ports:
      - "27017:27017"  # Expose MongoDB on port 35001
    depends_on:
      - kafka
    restart: always

  mongo-controller:
    container_name: mongo-controller
    build:
      context: consumers/
      dockerfile: mongodb/mongo-controller.Dockerfile
    depends_on:
      - kafka
      - mongo
    volumes: 
      - ./consumers/mongodb/main.py:/app/main.py
      - ./consumers/mongodb/mongodb_manager.py:/app/mongodb_manager.py
      - ./consumers/kafka_consumer.py:/app/kafka_consumer.py 
  
  youtube-producer:
    container_name: youtube-producer
    build:
      context: data/data_source/
      dockerfile: youtube/youtube.Dockerfile
    depends_on:
      - mongo
      - kafka


  trustpilot-producer:
    container_name: trustpilot-producer
    build:
      context: data/data_source/
      dockerfile: trustpilot/trustpilot.Dockerfile
    depends_on:
      - mongo
      - kafka
      
  reddit-producer:
    container_name: reddit-producer
    build:
      context: data/data_source/
      dockerfile: reddit/reddit.Dockerfile
    depends_on:
      - mongo
      - kafka
  
  spark-master:
    build:
        context: consumers
        dockerfile: spark/Dockerfile
    command: /bin/bash -c "./run_spark_job.sh"
    mem_limit: 1g
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - KAFKA_ADVERTISED_LISTENERS=kafka:9092
      - NUM_RECORDS=50
    ports:
      - "7077:7077" # Master port
      - "8080:8080" # Web UI
    volumes: 
      - ./consumers/spark/main.py:/app/main.py 
      - ./consumers/kafka_consumer.py:/app/kafka_consumer.py
    depends_on:
      - kafka

  spark-worker-1:
    build:
        context: consumers
        dockerfile: spark/Dockerfile
    mem_limit: 2g
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPAKR_WORKER_MEMORY=2g
    depends_on:
      - spark-master