services:  

  zookeeper:  #Zookeeper, a distributed coordination service used by Kafka.
    image: wurstmeister/zookeeper  # updated 5 years ago, but video said is stable version (consider bitnami)
    container_name: zookeeper  # Sets a custom name for the Zookeeper container, making it easier to reference.
    ports:
      - "2181:2181"  # Exposes port 2181 on both the host and the container. Port 2181 is used by Zookeeper to handle client connections.

  kafka: 
    image: wurstmeister/kafka
    container_name: kafka  
    ports:
      - "9092:9092"  
    environment:  # Defines environment variables that will be set inside the Kafka container.
      KAFKA_ADVERTISED_HOST_NAME: kafka # Sets the advertised hostname of the Kafka broker, here it's set to 'localhost', so Kafka can communicate on the local machine.
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # Specifies the address (host:port) of the Zookeeper service that Kafka will connect to. (it connects to the 'zookeeper' service running on port 2181 within the Docker Compose network)
      KAFKA_CREATE_TOPICS: "apple:1:1,nvidia:1:1"  # Define the topics here topic: apple:replication-factor=1:number-of-partitions=1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper

  mongo:
    image: mongo:6.0.5
    container_name: mongo
    ports:
      - "35001:27017"  # Expose MongoDB on port 35001
    depends_on:
      - zookeeper
      - kafka
    restart: always
    
  youtube-producer:
    ports: 
      - '5000:5000'
    container_name: youtube-producer
    build:
      context: data/data_source/youtube/
      dockerfile: youtube.Dockerfile
    depends_on:
      - zookeeper
      - kafka
      - mongo

  trustpilot-producer:
    ports: 
      - '5001:5001'
    container_name: trustpilot-producer
    build:
      context: data/data_source/trustpilot/
      dockerfile: trustpilot.Dockerfile
    depends_on:
      - zookeeper
      - kafka
      - mongo

  reddit-producer:
    ports: 
      - '5002:5002'
    container_name: reddit-producer
    build:
      context: data/data_source/reddit/
      dockerfile: reddit.Dockerfile
    depends_on:
      - zookeeper
      - kafka
      - mongo
  
