data:
  tp_train_path: "training/tp_training_dataset.json"
  tp_test_path: "training/tp_diff_companies_test_dataset.json"
  tp_simple: True
  yt_test_path: "training/yt_test_dataset.json"
  yt_train_path: "training/yt_train_dataset_balanced.json"
model_params:
  batch_size: 64
  trainable_transformer_layers: 5 # max is 6 for distilbert
  hf_model: "distilbert-base-uncased-finetuned-sst-2-english"
  weights_path: "None"
experiments:
  path: "training/experiments"
training:
  batch_size: 64
  lr: 2e-4
  epochs: 6
  tp_weight: 1
  yt_weight: 0.5
  tp_label_smoothing: 0.1
  yt_label_smoothing: 0.2