data:
  tp_train_path: "training/tp_training_dataset.json"
  tp_test_path: "training/tp_diff_companies_test_dataset.json"
  yt_test_path: "None"
  yt_train_path: "None"
model_params:
  batch_size: 256
  trainable_transformer_layers: 6 # max is 6 for distilbert
  lr: 2e-4
  epochs: 30
  path: "distilbert-base-uncased-finetuned-sst-2-english"